title: "Aurélien's personal website"
baseurl: https://aurelienooms.be
author:
  name: Aurélien Ooms
  email: aurelien.ooms@gmail.com
  url: https://aurelienooms.be

theme: portal

languageCode: en-us

params:
  # Style options: default (pink), blue, green, pink, red, sea, violet
  # Use custom.css for your custom styling
  style: blue
  name: Aurélien Ooms
  role: Human
  organization: Planet Earth
  portrait: img/portrait.jpg
  bio: >
    Do not take this page too unseriously. It is a portal to many important
    places on the internet.

  links:

    - url: https://research.aurelienooms.be
      title: Academic page
      description: My academic page. With papers, slides and stuff.
      image: https://ipfs.xn--mxac.cc/ipfs/QmSFUe5etCVrEyJDubD2uheHT5raD7MzYXY6Y8aqmhe1dw

    - url: https://papers.aurelienooms.be
      title: Papers
      description: List of scientific publications to which some contribution was made.
      image: https://ipfs.xn--mxac.cc/ipfs/Qmbr5qsfjDzCjyqb5rHPRErCnenih8Aisoi9gHez9J5mYE

    - url: https://barc.ku.dk
      title: BARC center
      description: >
        I used to have an office there. And when I say an office, I mean, the best office.
        Maybe the greatest in the history of officeship.
      image: https://ipfs.xn--mxac.cc/ipfs/QmXkZbvaGRYT6KS67aRTS6H7sYrbeQu135emRRkWfD8tno

    - url: https://algo.ulb.be
      title: Algorithms group
      description: >
        I used to have an office there. And when I say an office, I mean, the best office.
        Maybe the greatest in the history of officeship.
      image: https://ipfs.xn--mxac.cc/ipfs/QmVrNN6aNZNY8WS9Rrev49M8kWWAWmorzTn1JCb4J5ZdWe

    - url: mailto:aurelien.ooms@gmail.com
      description: >
        Only works for actual persons. No clever AI bot could go through my
        firewall... Do not even think about it.
        Here it is if you prefer the old school copy paste:
        __aurelien.ooms@gmail.com__
        Note that I did not replace the @ with an image.
      title: Electronic Mail
      image: https://ipfs.xn--mxac.cc/ipfs/QmPGDBxUp64pVpbjiy5Vo7SS8L4ALegZXfjxhGKEEBvDA3

    - url: https://math.aurelienooms.be
      title: Math
      description: My math weblog. Dumb yourself down before reading.
      image: https://ipfs.xn--mxac.cc/ipfs/QmcVx48jAyJLPiCuZRRiLG219LPhb6VhFRTVSkoqyDSSxV

    - url: https://blog.aurelienooms.be
      title: Blog
      description: My weblog. Might (not) be a waste of time.
      image: https://ipfs.xn--mxac.cc/ipfs/QmdChaHN53fppnBMc29j3UiCo1p99FehyasAHhEd75usXq

    - url: https://github.com/aureooms
      title: Github
      image: https://octodex.github.com/images/original.png
      description: >
        My Github page. Mostly JavaScript code and dotfiles. And this page, obviously.

    - url: https://linkedin.com/in/estelle-chasseloup-66a40499
      title: Estelle Chasseloup
      image: https://ipfs.xn--mxac.cc/ipfs/QmcoBxYCMKcPs3Et2RjUrbZp4vxdYvTAoz7CVJc8w6m2jD
      description: Just Estelle.

    - url: http://camillacs.piwigo.com
      title: Camillacs
      image: https://ipfs.xn--mxac.cc/ipfs/QmSWYFCdMvavVLuvfpAZzkmFZ4kpmKPiiAmLwRNvuLZ15M
      description: Estelle's father's photographs. Extrêmement joli.

    - url: https://en.wikipedia.org/wiki/Peyresq
      title: Peyresq
      image: https://ipfs.xn--mxac.cc/ipfs/QmQ18HyrHAyme4vX1LTNQxLKS6HU4p2Rs9n5NDzK9ixRdq
      description: >
        My flemish teacher once thought I misspelled Paris when writing about
        my summer vacation.
        Here is [the page in french](https://fr.wikipedia.org/wiki/Peyresq),
        the [organization to book for leisure](http://www.propeyresq.be),
        and the
        [organization to book for workshops](http://www.peiresc.org).


    - url: https://en.wikipedia.org/wiki/User:Aureooms
      description: My user page on Wikipedia. Not much activity for the moment.
      title: Wikipedia
      pad: yes
      image: https://ipfs.xn--mxac.cc/ipfs/QmSERYFEA7NGVfpAMXQzGvZp6yptUXb9EJyvK48bdu6Db2

    - url: https://projecteuler.net/profile/aureooms.png
      title: Project Euler
      image: https://ipfs.xn--mxac.cc/ipfs/QmVzQSdjXhmERTQbe2S33ifSxYZwaFjYs22wbocjYUYJmL
      description: It has been a long time I have made some progress on those...

    - url: https://stackoverflow.com/users/1582182/aurelien-ooms
      title: Stack Overflow
      image: https://ipfs.xn--mxac.cc/ipfs/QmXpeQbmRRLTVFsfnnFxWYUhSA6fpFNHm6qSQz9mh4us2p
      description: >
        I have not answered a single question since December 2014
        but my reputation keeps going up. Someone knows how to stop this?

    - url: https://keybase.io/aureooms
      title: Keybase
      image: https://ipfs.xn--mxac.cc/ipfs/QmZfiBFD8LQUJmuyoKj4kvBMt69ozgT3Q7maJev6Sy4VEm
      pad: yes
      description: >
        I do not even remember what this is for. Ah yes, some cool kid stuff.
        My PGP key is there.
        Does that even make sense?

    - url: https://aureooms-research.github.io/pats-game
      title: Pat's game solution zoo
      image: https://ipfs.xn--mxac.cc/ipfs/QmVtF284fAc25qCPoq5ADVLxfbGnC5BaGNMKwpKog1SPJN
      description: >
        [Website](https://aureooms-research.github.io/pats-game)
        displaying solutions for the game found in
        [OEIS sequence A070214](http://oeis.org/A070214).


    - url: http://homepages.ulb.ac.be/~slanger/cg/hsaureooms/def.html
      title: Ham-Sandwich cuts
      image: https://ipfs.xn--mxac.cc/ipfs/QmSVsPBSQjsJM4bew4zB8JqiGpF984gfjFwbAAUd7MMWQ2
      description: Computational Geometry project from back in the dayz (2014).

    - url: https://ipfs.xn--mxac.cc/ipfs/QmaEaS5ATPpQfFrc9WVAP9n6ZVFUNZGxTtP46ntruEfFhM
      title: Fishtube
      image: https://ipfs.xn--mxac.cc/ipfs/QmNapSHCRJ2K5DsGoQHfEHhRUhxVUyqGdzYiZkfsKnSrj4
      description: Some fine coding right there (2013).
