title: "Aurélien's personal website"
baseurl: https://aureooms.github.io
author:
  name: Aurélien Ooms
  email: aurelien.ooms@gmail.com
  url: https://aureooms.github.io

theme: portal

languageCode: en-us

params:
  # Style options: default (pink), blue, green, pink, red, sea, violet
  # Use custom.css for your custom styling
  style: blue
  name: Aurélien Ooms
  role: PhD student
  organization: Université libre de Bruxelles
  portrait: img/portrait.jpg
  bio: >
    Do not take this page too unseriously. It is a portal to many important
    places on the internet.

  links:

    - url: http://homepages.ulb.ac.be/~aureooms
      title: Academic page
      description: My academic page. With papers, slides and stuff.
      image: https://ipfs.io/ipfs/Qmbr5qsfjDzCjyqb5rHPRErCnenih8Aisoi9gHez9J5mYE

    - url: https://algo.ulb.be
      title: Algorithms group
      description: >
        I have an office there. And when I say an office, I mean, the best office.
        Maybe the greatest in the history of officeship.
      image: https://ipfs.io/ipfs/QmVrNN6aNZNY8WS9Rrev49M8kWWAWmorzTn1JCb4J5ZdWe

    - url: mailto:aurelien.ooms@gmail.com
      description: >
        Only works for actual persons. No clever AI bot could go through my
        firewall... Do not even think about it.
        Here it is if you prefer the old school copy paste:
        __aurelien.ooms@gmail.com__
        Note that I did not replace the @ with an image.
      title: Electronic Mail
      image: https://ipfs.io/ipfs/QmPGDBxUp64pVpbjiy5Vo7SS8L4ALegZXfjxhGKEEBvDA3

    - url: /math
      title: Math
      description: My math weblog. Dumb yourself down before reading.
      image: https://ipfs.io/ipfs/QmcVx48jAyJLPiCuZRRiLG219LPhb6VhFRTVSkoqyDSSxV

    - url: https://github.com/aureooms
      title: Github
      image: https://octodex.github.com/images/original.png
      description: >
        My Github page. Mostly JavaScript code and dotfiles. And this page, obviously.

    - url: https://linkedin.com/in/estelle-chasseloup-66a40499
      title: Estelle Chasseloup
      image: https://ipfs.io/ipfs/QmcoBxYCMKcPs3Et2RjUrbZp4vxdYvTAoz7CVJc8w6m2jD
      description: Just Estelle.

    - url: http://camillacs.piwigo.com
      title: Camillacs
      image: https://ipfs.io/ipfs/QmSWYFCdMvavVLuvfpAZzkmFZ4kpmKPiiAmLwRNvuLZ15M
      description: Estelle's father's photographs. Extrêmement joli.

    - url: https://en.wikipedia.org/wiki/Peyresq
      title: Peyresq
      image: https://ipfs.io/ipfs/QmQ18HyrHAyme4vX1LTNQxLKS6HU4p2Rs9n5NDzK9ixRdq
      description: >
        My flemish teacher once thought I misspelled Paris when writing about
        my summer vacation.
        Here is [the page in french](https://fr.wikipedia.org/wiki/Peyresq),
        the [organization to book for leisure](http://www.propeyresq.be),
        and the
        [organization to book for workshops](http://www.peiresc.org).


    - url: https://en.wikipedia.org/wiki/User:Aureooms
      description: My user page on Wikipedia. Not much activity for the moment.
      title: Wikipedia
      pad: yes
      image: https://ipfs.io/ipfs/QmSERYFEA7NGVfpAMXQzGvZp6yptUXb9EJyvK48bdu6Db2

    - url: https://projecteuler.net/profile/aureooms.png
      title: Project Euler
      image: https://ipfs.io/ipfs/QmVzQSdjXhmERTQbe2S33ifSxYZwaFjYs22wbocjYUYJmL
      description: It has been a long time I have made some progress on those...

    - url: https://stackoverflow.com/users/1582182/aurelien-ooms
      title: Stack Overflow
      image: https://ipfs.io/ipfs/QmXpeQbmRRLTVFsfnnFxWYUhSA6fpFNHm6qSQz9mh4us2p
      description: >
        I have not answered a single question since December 2014
        but my reputation keeps going up. Someone knows how to stop this?

    - url: https://keybase.io/aureooms
      title: Keybase
      image: https://ipfs.io/ipfs/QmZfiBFD8LQUJmuyoKj4kvBMt69ozgT3Q7maJev6Sy4VEm
      pad: yes
      description: >
        I do not even remember what this is for. Ah yes, some cool kid stuff.
        My PGP key is there.
        Does that even make sense?

    - url: http://aureooms.wolkom.net
      title: Old page
      image: https://ipfs.io/ipfs/QmTfsNvspEftzAMmmop5paxAMdaGNGFb86r8oQ1q76vRWf
      description: Will get rid of it at some point.

    - url: https://aureooms-research.github.io/pats-game
      title: Pat's game solution zoo
      image: https://ipfs.io/ipfs/QmV3CVP7y7n4wTEHDpaaLnEnfxEPH1iPZJfHshG6fDqV7f
      description: >
        [Website](https://aureooms-research.github.io/pats-game)
        displaying solutions for the game found in
        [OEIS sequence A070214](http://oeis.org/A070214).


    - url: http://homepages.ulb.ac.be/~slanger/cg/hsaureooms/def.html
      title: Ham-Sandwich cuts
      image: https://ipfs.io/ipfs/QmSVsPBSQjsJM4bew4zB8JqiGpF984gfjFwbAAUd7MMWQ2
      description: Computational Geometry project from back in the dayz (2014).

    - url: http://aureooms.wolkom.net/infof521/#!
      title: Chinese postman
      image: https://ipfs.io/ipfs/Qme2rxbnN5Db3vAhwU4pqoYenKvuRLCYZjyR93xHaBGcTv
      description: Graph optimization project from back in the dayz (2014).

    - url: https://ipfs.io/ipfs/QmaEaS5ATPpQfFrc9WVAP9n6ZVFUNZGxTtP46ntruEfFhM
      title: Fishtube
      image: https://ipfs.io/ipfs/QmNapSHCRJ2K5DsGoQHfEHhRUhxVUyqGdzYiZkfsKnSrj4
      description: Some fine coding right there (2013).
