name = "portal"
license = "MIT"
licenselink = "https://github.com/aureooms/hugo-portal/blob/master/LICENSE"
description = "Landing page with links"
homepage = "https://github.com/aureooms/hugo-portal"
tags = ["minimal", "responsive"]
features = ["bootstrap", "responsive"]
min_version = 0.17

[author]
  name = "Aurélien Ooms"
  homepage = "https://aureooms.github.io"

# If porting an existing theme
[original]
  name = "Kishan B"
  homepage = "https://github.com/kishaningithub"
